export const metadata = {
  title: "AnonMessage",
  description: "Generated by Hardik Chaudhary",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
