import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "AnonMessage",
  description: "Generated by Hardik Chaudhary",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <main className="flex-grow">{children}</main>
    </>
  );
}
